<%

ss_path = "./screenshots/"
FileUtils.mkdir("./screenshots") unless File.exists?("./screenshots")

if ENV["USER"] == "jenkins"
  formatter = "progress"
else
  formatter = "Slowhandcuke::Formatter"
end

calabash_dir = "#{ENV['HOME']}/.calabash"

devices = {}

device_list = ['iphone5C_80', 'iphone5S_71', 'iphone4S_80', 'iphone6', 'iphone6plus']

device_list.each do |device|
  dir = "#{calabash_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid}
  devices[device.to_sym] = ht
end

%>

ss_path: SCREENSHOT_PATH=<%= ss_path %>
common:        -p ss_path -f <%= formatter %> NO_STOP=1

simulator:     -p common -p ss_path --tags ~@device_only --tags ~@device APP=./BikeTag.app
default:       -p simulator

# required only for devices
bundle_id:    BUNDLE_ID=me.jackpine.BikeTag.Debug

device:      -p common -p bundle_id --tags ~@simulator --tags ~@simulator_only

iphone5C_80: -p device DEVICE_TARGET=<%= devices[:iphone5C_80][:udid] %> DEVICE_ENDPOINT=<%= devices[:iphone5C_80][:ip] %>
iphone5S_71: -p device DEVICE_TARGET=<%= devices[:iphone5S_71][:udid] %> DEVICE_ENDPOINT=<%= devices[:iphone5S_71][:ip] %>
iphone4S_80: -p device DEVICE_TARGET=<%= devices[:iphone4S_80][:udid] %> DEVICE_ENDPOINT=<%= devices[:iphone4S_80][:ip] %>
iphone6:     -p device DEVICE_TARGET=<%= devices[:iphone6][:udid] %>     DEVICE_ENDPOINT=<%= devices[:iphone6][:ip] %>
iphone6plus: -p device DEVICE_TARGET=<%= devices[:iphone6plus][:udid] %> DEVICE_ENDPOINT=<%= devices[:iphone6plus][:ip] %>

# Joshua's devices
neptune: -p iphone4S_80
saturn:  -p iphone5S_71
hat:     -p iphone6
denis:   -p iphone6plus
